name: IA Workflow
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main
env:
  # Token con permisos dentro de la ORG
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Variable donde coger el audit file
  AUDIT_REPOSITORY: bitbucket-audit
  # Owner del repositorio
  REPOSITORY_OWNER: ${{ github.repository_owner }}
  CHECKOUT_HEAD_PATH: head
  CHECKOUT_AUDIT_PATH: audit
concurrency:
  group: ia-workflow
  cancel-in-progress: false

jobs:
    check-successful-status:
      runs-on: ubuntu-latest
      outputs: 
        FILE_NAME: ${{ steps.file.outputs.FILE_NAME }}
        SUCCESSFUL: ${{ steps.successful.outputs.SUCCESSFUL }}
      steps:
        - name: GET Files
          id: file
          run: |
            response=$(curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ env.GH_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/pruebas-para-todos/target-repository/pulls/${{ github.event.pull_request.number }}/files)
            echo "$response"
            file_names=$(echo "$response" | jq -r '.[] | .filename')
            echo $file_names
            echo "FILE_NAME=$file_names" >> $GITHUB_OUTPUT
        - name: Checkout file
          uses: actions/checkout@v4
          with:
            path: ${{ env.CHECKOUT_HEAD_PATH }}
            ref: ${{ github.head_ref }}
            sparse-checkout: ${{ steps.file.outputs.FILE_NAME }}
        - name: Checkout audit file
          uses: actions/checkout@v4
          with:
            path: ${{ env.CHECKOUT_AUDIT_PATH }}
            repository: ${{ env.REPOSITORY_OWNER }}/${{ env.AUDIT_REPOSITORY }}
            sparse-checkout: README.md
        - name: Check if PR is from Build or Deployment
          id: path
          run: |
            name=$(yq -e .name ${{ env.CHECKOUT_HEAD_PATH }}/${{ steps.file.outputs.FILE_NAME }})
            echo "Este es el nombre: $name"
            if [[ $name == *"/"* ]]; then
              echo "Es un plan: $name"
              project=$(echo $name | cut -d'/' -f1)
              plan=$(echo $name | cut -d'/' -f2)
              echo "FILE_PATH=build/$project/$plan/" >> $GITHUB_OUTPUT
            else
              cut_name=$(echo "$name" | cut -d'_' -f1)
              echo "Es un deployment: $cut_name"
              echo "FILE_PATH=deployment/$cut_name/" >> $GITHUB_OUTPUT
            fi
        - name: Check if that YML is successful
          id: successful
          working-directory: ${{ env.CHECKOUT_AUDIT_PATH }}
          run: |
            awk '/### Successful/{p=1} /### Partially successful/{p=0} p' README.md > successful.md
            cat successful.md
            successful=$(cat successful.md)
            if [[ $successful == *"${{ steps.path.outputs.FILE_PATH }}"* ]]; then
              echo "Es successful"
              echo "SUCCESSFUL=true" >> $GITHUB_OUTPUT
            else
              echo "No es successful"
              echo "SUCCESSFUL=false" >> $GITHUB_OUTPUT
            fi
    execute-ia:
      if: needs.check-successful-status.outputs.successful == 'false'
      needs: check-successful-status
      uses: pruebas-para-todos/Migration-Bitbucket-Bamboo/.github/workflows/RW_AI_PYTHON_REPAIR_WORKFLOW.yml@main
      with:
        REMOTE_REPO_NAME: ${{ github.event.repository.name }}
        BRANCH_NAME: ${{ github.head_ref }}
        PATH_WORKFLOW_FILE: ${{ needs.check-successful-status.outputs.SUCCESSFUL}}



            


            
            
            
            
            


